### ISSUE TITLE
Remora 1.3.5 problème de requête

### ISSUE THREAD

**Issue by DanoneKiD** [lunarok/jeedom_remora#7]
Bonjour @lunarok 

Depuis la version 1.3.5 du soft de la remora les requêtes http ne fonctionnent plus.
La fonction `file();` n'abouti pas.
Je pense qu'il y a un problème de content-type ou un truc du genre.
 
J'ai ouvert une issue et un post chez charles
https://community.ch2i.eu/topic/251/probl%C3%A8me-de-communication-jeedom-avec-1-3-5
https://github.com/hallard/remora_soft/issues/29

Pour contourner le problème je t'ai fait un PR pour utiliser la classe `com_http`du core pour effectuer les requêtes vers la remora.

Merci

**Comment by lunarok** [comment]
jeedom
